
spring:
  application:
    name: order_service
  grpc:
    server:
      enabled: false
    client:
      channels:
        payment:
          address: "localhost:9090"
          negotiation-type: plaintext
server:
   port: 8081

